name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate and submit dependency graph
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: gradle/actions/dependency-submission@v4

      - name: Start kafka
        run: make start-kafka

      - name: Build with Gradle
        run: ./gradlew clean :kotlin-kafka-client-common:build :kotlin-kafka-client-core:build :kotlin-kafka-client-lowlevel:build :kotlin-kafka-client-transport:build --max-workers=10

      - name: Run integration test
        run: ./gradlew :test:integration-test:build

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          include_passed: true
          detailed_summary: true
          report_paths: '**/build/test-results/*/TEST-*.xml'
